name: check

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install/Update Tex Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            latex latex-bin scheme-small koma-script luatexbase luatex babel babel-german pgf enumitem
      - name: First runs
        run: |
          lualatex gitgame-de
          lualatex gitgame-de_Vorderseiten.tex
          lualatex gitgame-de_Rueckseite.tex
      - name: Second run
        run: lualatex gitgame-de
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: gitgame-de.pdf
      - name: Prepare build directory
        run: |
          mkdir build
          cp gitgame-de.pdf build/
          cp gitgame-de_Vorderseiten.pdf build/
          cp gitgame-de_Rueckseite.pdf build/
      - name: Upload to GitHub-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
